plugins {
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
}

group 'info.mastera'
version '1.0.7.2'
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"

    implementation("org.telegram:telegrambots-springboot-longpolling-starter:$telegramVersion") {
        exclude group: 'org.apache.commons', module: 'commons-lang3'
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk18on'
    }
    implementation "org.telegram:telegrambots-extensions:$telegramVersion"
    implementation "org.telegram:telegrambots-client:$telegramVersion"

    implementation "org.apache.commons:commons-lang3:$commonLangVersion"
    implementation "org.bouncycastle:bcprov-jdk18on:$bouncycastleVersion"

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation 'org.liquibase:liquibase-core'
    runtimeOnly "org.mariadb.jdbc:mariadb-java-client:$mariadbClientVersion"

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'com.vaadin.external.google', module: 'android-json'
    }
}

tasks.named('test') {
    useJUnitPlatform()
    systemProperty "file.encoding", "utf-8"
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}
