server:
  port: 8080
spring:
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    default-schema: public
telegram:
  username: ${TELEGRAM_USERNAME:}
  token: ${TELEGRAM_TOKEN:}