server:
  port: 8080
spring:
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
telegram:
  username: ${TELEGRAM_USERNAME:}
  token: ${TELEGRAM_TOKEN:}
  send-retries: ${TELEGRAM_SEND_RETRIES:3}
  send-retry-delay: ${TELEGRAM_SEND_RETRY_DELAY:5000}