version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: border-state-bot-postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - border-state-bot-postgres:/var/lib/postgresql/data

  border-state-collector-app:
    container_name: border-state-bot-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    ports:
      - '8088:8080'
    depends_on:
      - postgres

volumes:
  border-state-bot-postgres: