version: '3.8'

services:

  border-state-bot-app:
    container_name: border-state-bot-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
    environment:
      - DATASOURCE_URL=jdbc:mariadb://host.docker.internal:3306/${POSTGRES_DB}
    ports:
      - '8088:8080'
