version: '3.8'

services:

  border-state-bot-app:
    container_name: border-state-bot-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
    ports:
      - '8088:8080'
