version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: border-state-bot-postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - border-state-bot-postgres:/var/lib/postgresql/data

volumes:
  border-state-collector-postgres: